services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root 
      - POSTGRES_DB=us_accidents
    volumes:
      [./accidents_postgres_data:/var/lib/postgresql/data:rw]
    ports:
      - "5431:5432" #[5432:5432]
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      [8081:80] #[8080:80]